# Generated by Django 5.1.7 on 2025-03-21 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='games')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PLAYING', 'Playing'), ('FINISHED', 'Finished')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('figure', models.ImageField(blank=True, null=True, upload_to='figures')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='engine.game')),
            ],
            options={
                'unique_together': {('game', 'name')},
            },
        ),
    ]
